# fly.toml app configuration file generated for green-cherry-4026 on 2023-06-02T14:55:12+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "green-cherry-4026"
primary_region = "arn"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    restart_limit = 0
    path = "/foods/apple"
